@startwbs 豪華な夕食を作る
title 豪華な夕食を作るwbs
*[#yellow] 夕食を食べる
**[#LightSkyBlue] カレーを作る
*** ご飯を炊く
*** 材料を切る
*** 材料を炒める
*** 食材を煮る
*** 味付けをする
*** 盛り付けをする
**[#LightSkyBlue] サラダ&焼きりんごを作る
*** サラダの材料を切る
*** サラダの盛り付け（味付け）をする
*** りんごを切る
*** りんごを焼く
*** 焼きりんごを盛り付ける
**[#LightSkyBlue] 買い出しをする
*** お金をおろす
*** 買い物をする
**[#LightSkyBlue] スープを作る
*** 材料を切る
*** 材料を煮る
*** スープの味付けをする
*** 盛り付ける
@endwbs

