@startuml 豪華な夕飯を作る
start
fork
    :銀行でお金をおろす(太郎さん);
    :スーパーで買い物をする(太郎さん,次郎さん);
fork again
    :米を洗う(花子さん);
    :炊飯器にセットして米を炊く(花子さん);
end fork
fork
    :カレーの材料を切る(花子さん);
    :カレーの材料を炒める(花子さん);
    :カレーの材料を煮る(花子さん);
    :味付けをする(花子さん);
    :盛り付けをする(花子さん);
fork again
    :サラダの材料を切る(次郎さん);
    :サラダの盛り付けと味付けをする(次郎さん);
    :リンゴを切る(次郎さん);
    :リンゴを焼く(次郎さん);
    :焼きリンゴを盛り付ける(次郎さん);
fork again
    :スープの材料を切る(太郎さん);
    :スープの材料を煮る(太郎さん);
    :スープの味付けをする(太郎さん);
    :スープを盛り付ける(太郎さん);
end fork
stop
@enduml
